name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    permissions:
      contents: write
      pages: write
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Checkout SPHT
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          repository: agriyakhetarpal/scientific-python-hugo-theme
          submodules: recursive
          ref: spec-14
          path: spht
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0

      - name: Install Hugo
        run: pip install hugo

      - name: Set up dart-sass
        run: |
          export DART_SASS_VERSION="1.83.4"
          export DART_SASS_TARBALL="dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"
          export DART_SASS_URL="https://github.com/sass/dart-sass/releases/download"
          cd /tmp && \
          curl -LJO ${DART_SASS_URL}/${DART_SASS_VERSION}/${DART_SASS_TARBALL} && \
          tar -xf ${DART_SASS_TARBALL} && \
          rm ${DART_SASS_TARBALL}
          echo "/tmp/dart-sass" >> $GITHUB_PATH

      - name: Build static site
        working-directory: spht
        run: make main

      - name: Copy static site
        run: |
          mkdir -p dist
          cp -r spht/main/public/* dist/

      - name: Upload assets for debugging
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: specs-${{ github.run_id }}
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: agriyakhetarpal
          user_email: "74401230+agriyakhetarpal@users.noreply.github.com"
